# PowerShell script to execute the staging plan
# Generated by git-staging-plan.ps1

# Update .gitignore
git add .gitignore
git commit -m 'Update .gitignore to exclude generated and temporary files'
# Core Configuration Files
# Essential configuration files for the project
git add package.json package-lock.json tsconfig.json turbo.json .prettierrc
git commit -m 'Add core configuration files'
# UI Package
# UI components and styles
git add packages/ui/
git commit -m 'Add UI package implementation'
# Content Packages
# Content-related packages
git add packages/content-storage/ packages/content-transformer/ packages/table-transformer/
git commit -m 'Add content-related packages'
# Reference Parser Package
# Reference parser implementation
git add packages/reference-parser/
git commit -m 'Add reference parser package'
# Data Models Package
# Data models and types
git add packages/data-models/
git commit -m 'Add data models package'
# Audio Services Package
# Audio services implementation
git add packages/audio-services/
git commit -m 'Add audio services package'
# Reader App
# Reader application
git add apps/reader/
git commit -m 'Add reader application'
# UB Reader App
# UB Reader application
git add apps/ub-reader/
git commit -m 'Add UB Reader application'
# Publications App
# Publications application
git add apps/publications/
git commit -m 'Add publications application'
# Almanac App
# Almanac application
git add apps/almanac-new/
git commit -m 'Add almanac application'
# Content Files
# Content files for the applications
git add content/
git commit -m 'Add content files'
# Documentation
# Documentation files
git add *.md docs/
git commit -m 'Add documentation files'
# Scripts
# Utility scripts
git add scripts/
git commit -m 'Add utility scripts'
# Configuration
# Configuration files
git add config/
git commit -m 'Add configuration files'
# Remaining Files
# Any remaining files that should be tracked
git add .
git commit -m 'Add remaining files'

