name: Lighthouse CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm@8.6.3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies with --no-frozen-lockfile
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Build with --no-lint to skip linting
      - name: Build
        run: pnpm build

      # Start server
      - name: Start server
        run: pnpm --filter=ub-reader start & npx wait-on http://localhost:3000

      # Run Lighthouse CI
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
